print("Universitas Bina Sarana Informatika".lower())
print("Universitas Bina Sarana Informatika".upper())
print("I Love Programming in Python".split())
print("I Love Python".startswith("I"))
print("Saya belajar Python".endswith("on"))
print(' - '.join(['I', 'love', 'you']))
print("Belajar Java di BSI".replace('Java','Python'))