print("==============================")
print("Name = Rahmat Hidayat Sianturi")
print("Kelas = 19.1A.21")
print("Jurusan = Sistem Informasi")
print("Hoby = Travel and Run")
print("Goals = Financial Freedom")
print("==============================")